TD
    "tt::runtime::system_desc::getCurrentSystemDesc" -- "instantiates" --> "tt::tt_metal::distributed::MeshDevice"
    "tt::tt_metal::distributed::MeshDevice" -- "provides_data_to" --> "getAllDeviceConnections"
    "tt::tt_metal::distributed::MeshDevice" -- "provides_data_to" --> "getCurrentSystemDescImpl"
    "getCurrentSystemDescImpl" -- "invokes" --> "calculateDRAMUnreservedEnd"
    "getCurrentSystemDescImpl" -- "uses" --> "flatbuffers::FlatBufferBuilder"
    "flatbuffers::FlatBufferBuilder" -- "outputs" --> "system_desc.ttsys"
