graph TD
    idA["Device::Device()"]
    idB["Device::initialize_allocator()"]
    idC["L1BankingAllocator::generate_config()"]
    idD["Device::configure_command_queue_programs()"]

    idA --> idB
    idB --> idC
    idC --> idD
