graph TB
    Start["compute_kernel_hw_startup(icb0, icb1, ocb)"]
    
    UnpackConfig["UNPACK Thread (TRISC0):<br/>llk_unpack_hw_configure(icb0, icb1)"]
    
    MathSync["MATH Thread (TRISC1):<br/>llk_math_pack_sync_init()"]
    MathConfig["MATH Thread (TRISC1):<br/>llk_math_hw_configure(icb0, icb1)"]
    
    PackConfig["PACK Thread (TRISC2):<br/>llk_pack_hw_configure(ocb)"]
    PackInit["PACK Thread (TRISC2):<br/>llk_pack_init(ocb)"]
    
    Sentinel["ComputeKernelSentinel:<br/>Record CB associations"]
    
    End["Initialization Complete"]
    
    Start --> UnpackConfig
    UnpackConfig --> MathSync
    MathSync --> MathConfig
    MathConfig --> PackConfig
    PackConfig --> PackInit
    PackInit --> Sentinel
    Sentinel --> End


Sources: [tt_metal/hw/firmware/src/tt-2xx/dm.cc:87-101](), [tt_metal/hw/firmware/src/tt-2xx/trisc.cc:98-109]()