graph TB
    Input["Workflow inputs<br/>repo, release_type, new_version_tag, branch"]
    SetFacts["set-release-facts<br/>Configure based on release_type"]
    CheckExists["check_release.sh<br/>Skip if exists & !overwrite"]
    UpliftArtifacts["uplift-artifacts or wait-on-tt-pypi-wheels<br/>Retrieve dependencies"]
    BuildWheel["build-release-wheel<br/>Create Python packages"]
    BuildDocker["docker-build-push<br/>Create container image"]
    
    Input --> SetFacts
    SetFacts --> CheckExists
    CheckExists -->|"release does not exist"| UpliftArtifacts
    UpliftArtifacts --> BuildWheel
    BuildWheel --> BuildDocker


[.github/workflows/release.yml:78-184]()