TB
    QFW["QuasarFunctionalWorkerBlock"]
    
    NEO0["QuasarFunctionalNeoBlock<br/>neo_id: 0<br/>Base: 0x01800000"]
    NEO1["QuasarFunctionalNeoBlock<br/>neo_id: 1<br/>Base: 0x01810000"]
    NEO2["QuasarFunctionalNeoBlock<br/>neo_id: 2<br/>Base: 0x01820000"]
    NEO3["QuasarFunctionalNeoBlock<br/>neo_id: 3<br/>Base: 0x01830000"]
    
    T00["trisc0<br/>risc_id: 0"]
    T01["trisc1<br/>risc_id: 1"]
    T02["trisc2<br/>risc_id: 2"]
    T03["trisc3<br/>risc_id: 3"]
    
    QFW --> NEO0
    QFW --> NEO1
    QFW --> NEO2
    QFW --> NEO3
    
    NEO0 --> T00
    NEO0 --> T01
    NEO0 --> T02
    NEO0 --> T03
